### PR TITLE
upgrade to pytorch 0.4

### PR DESCRIPTION
**Pull request by jiangwei221**
I have pytorch 0.4 on my computer, and if I directly run the code, if will give me some error.
I tried to upgrade it.
It seems working fine now.

### CODE REVIEW

**Comment by chenhsuanlin** [comment]
Could you please provide the error message you're getting? It's working fine on my side.

**Comment by jiangwei221** [comment]
The CNN and STN options are working, but the IC-STN option is not working on my side. 
```
Commad: python train.py IC-STN
Python version: Python 3.6.6 :: Anaconda, Inc.
Pytorch version: 0.4.1.post2
Numpy version: 1.15.1
Error:
=======================================================
train.py (training on MNIST)
=======================================================
setting configurations...
(0) test
------------------------------------------
network type: IC-STN, recurrent warps: 4
batch size: 100, image size: 28x28
warpScale: (pert) 0.25 (trans) 0.25
[geometric predictor]    stddev=1e-01, lr=1e-04
[classification network] stddev=1e-01, lr=1e-02
------------------------------------------
training model (0) test...
building network...
loading MNIST dataset...
======= TRAINING START =======
start training...
Traceback (most recent call last):
  File "train.py", line 75, in <module>
    train_loss.backward()
  File "/home/jiangwei/miniconda3/envs/venv_tf/lib/python3.6/site-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/jiangwei/miniconda3/envs/venv_tf/lib/python3.6/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: Expected a Tensor of type Variable but found an undefined Tensor at position #2 for iterable argument #0 'tensors'
```

**Comment by shahabty** [comment]
Hello,
I have the same problem with pytorch 0.4.1
The error message is: 
RuntimeError: Expected a Tensor of type Variable but found an undefined Tensor at position #2 for iterable argument #0 'tensors'

**Comment by jiangwei221** [comment]
maybe this would help:
https://github.com/chenhsuanlin/inverse-compositional-STN/pull/9/commits/f9528af7509d1f36821c2724c524588986058fcf

**Pull request closed without merging**
